---
# Vagrant config.
vagrant_ip: 192.168.40.15
vagrant_memory: 1024
vagrant_cpus: 2

# Drupal settings
drupal_domain: "dcm15.local"
drupal_core_path: "/drupal/docroot"
drupal_site_name: "DrupalCampMelbourne 2015"
drupal_install_profile: drupalcampmel
drupal_enable_modules: []
drupal_account_name: vagrant
drupal_account_pass: vagrant
drush_makefile_path: /drupal/stub.make
build_makefile: true
install_site: true

# Apache config
apache_vhosts:
  - {servername: "{{ drupal_domain }}", documentroot: "{{ drupal_core_path }}"}

# Symlinks
symlinks:
  - src: /drupal/modules/custom
    link: /drupal/docroot/profiles/drupalcampmel/modules/custom
    force: yes
  - src: /drupal/themes/custom
    link: /drupal/docroot/profiles/drupalcampmel/themes/custom
    force: yes